#!/bin/python3

username = input("what is your username : ")
password = input("Enter password : ")
password_lenght = len(password)

hide_password = '*' * password_lenght
print(f'{username} the lenght of your password is {password_lenght} and your password is {hide_password}')

print(hide_password)
